apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: k9-innsyn-dine-pleiepenger-mikrofrontend-ssr # Change this to your application name
    namespace: dusseldorf # Change this to your namespace
    labels:
        team: dusseldorf # Change this to your team name
spec:
    observability:
        autoInstrumentation:
            enabled: true
            runtime: nodejs
    tokenx:
        enabled: true
    image: {{ image }}
    port: 3000
    liveness:
        path: /api/internal/isAlive
        initialDelay: 10
    readiness:
        path: /api/internal/isReady
        initialDelay: 10
    replicas:
        min: 2
        max: 4
    accessPolicy:
        inbound:
            rules:
                - application: tms-min-side
                  namespace: min-side
    resources:
        limits:
            memory: 768Mi
        requests:
            cpu: '20m'
            memory: 128Mi
    env:
        - name: DINE_PLEIEPENGER_URL
          value: 'https://dine-pleiepenger.intern.dev.nav.no'
